### ISSUE TITLE
Error when creating new child task

### ISSUE THREAD

**Issue by apocalypsebg** [Eficent/eficent-odoo-addons#13]
When  I attempt to create a task in a WBS project (in this case a child task to a work package), I receive the following error. This is on OpenERP 7.0

``` python
Client Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1128, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/opt/openerp/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/addons-eficent/project_time_schedule/project_time_schedule.py", line 62, in onchange_stage_id
    cr.execute('select state from project_task_type where id = %s', (stage_id,))
  File "/opt/openerp/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: select state from project_task_type where id = false
                                                     ^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

This are the Eficent modules that are installed:

| Technical Name | Sequence | Installed Version |
| --- | --- | --- |
| project_change_state | 100 | 7.0.1.0 |
| project_time_easy_scheduling | 100 | 7.0.1.0 |
| project_wbs_task | 100 | 7.0.2.0 |
| project_progress_measurement | 100 | 7.0.1.0 |
| project_percent_completed | 100 | 7.0.1.0 |
| project_wbs | 100 | 7.0.2.0 |
| project_update_child_state | 100 | 7.0.1.0 |
| project_time_milestone | 100 | 7.0.1.0 |
| project_communications_meetings | 100 | 7.0.1.0 |
| hr_timesheet_analysis_wbs | 100 | 7.0.1.0 |
| project_time_sequence | 100 | 7.0.1.0 |
| project_time_schedule | 100 | 7.0.2.0 |
| progress_measurement | 100 | 7.0.1.0 |
| hr_timesheet_sheet_import_accounts | 100 | 7.0.1.0 |
| hr_timesheet_sheet_approvers | 100 | 7.0.1.0 |
| project_change_state_child | 100 | 7.0.1.0 |
| account_invoice_analysis_inv_number | 100 | 7.0.0.1 |
| account_invoice_analysis_analytic | 100 | 7.0.0.1 |

**Comment by AaronHForgeFlow** [comment]
Could not reproduce. Closed due to inactivity. If this is still happening feel free to reopen it with the steps to reproduce.
